### ISSUE TITLE
Device not showing in Motionbuilder 2017 or 2018

### ISSUE THREAD

**Issue by fikkle** [ue4plugins/MobuLiveLink#13]
Hi, trying to set up LiveLink in motionbuilder, I add the folder successfully and get the pop up telling me to restart but the device does not show up...? I am using the Educational version of Mobu, but that has never stopped me using any other plugins and we constantly use Vicon's data stream plugin plus others fine...

**Comment by subTropic** [comment]
I am having the exact same problem, any ideas?

**Comment by MotionRapture** [comment]
I had the same issue.

The fix for me was making sure this directory structure existed:
C:\Users\<username>\Documents\MB\<version>-x64\config
(The version is just the year eg. 2018)

If its not there, mobu can't update its preferences, as that where it expects the application.txt to be.
I am assuming my admin got this directory structure when they installed mobu, but other users don't necessarily get it, maybe user and/or security structures/setups prevent it?

**Comment by subTropic** [comment]
Yes that was it, plug-in install silently fails if the config directory doesn't already exist. Fix is to just create the directory manually!
